export interface DutchClub {
  id: string;
  name: string;
  shortName: string;
  code: string;
  city: string;
  primaryColor: string;
  secondaryColor: string;
  logoUrl: string;
  league: "eredivisie" | "eerste_divisie" | "amateur" | "other";
}

// Logo URLs via Wikipedia Wikimedia Commons (free, no API key needed)
export const DUTCH_CLUBS: DutchClub[] = [
  // ── Eredivisie ────────────────────────────────────────────────────────────
  {
    id: "ajax",
    name: "AFC Ajax",
    shortName: "Ajax",
    code: "AJX",
    city: "Amsterdam",
    primaryColor: "#D2122E",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/7/79/Ajax_Amsterdam.svg/100px-Ajax_Amsterdam.svg.png",
    league: "eredivisie",
  },
  {
    id: "psv",
    name: "PSV Eindhoven",
    shortName: "PSV",
    code: "PSV",
    city: "Eindhoven",
    primaryColor: "#E31E2E",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/PSV_Eindhoven.svg/100px-PSV_Eindhoven.svg.png",
    league: "eredivisie",
  },
  {
    id: "feyenoord",
    name: "Feyenoord",
    shortName: "Feyenoord",
    code: "FEY",
    city: "Rotterdam",
    primaryColor: "#C8102E",
    secondaryColor: "#004B87",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Feyenoord_Logo.svg/100px-Feyenoord_Logo.svg.png",
    league: "eredivisie",
  },
  {
    id: "az",
    name: "AZ Alkmaar",
    shortName: "AZ",
    code: "AZ",
    city: "Alkmaar",
    primaryColor: "#E31E2E",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/AZ.svg/100px-AZ.svg.png",
    league: "eredivisie",
  },
  {
    id: "utrecht",
    name: "FC Utrecht",
    shortName: "Utrecht",
    code: "UTR",
    city: "Utrecht",
    primaryColor: "#CC0000",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/FC_Utrecht.svg/100px-FC_Utrecht.svg.png",
    league: "eredivisie",
  },
  {
    id: "twente",
    name: "FC Twente",
    shortName: "Twente",
    code: "TWN",
    city: "Enschede",
    primaryColor: "#E31E2E",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1a/FC_Twente.svg/100px-FC_Twente.svg.png",
    league: "eredivisie",
  },
  {
    id: "vitesse",
    name: "Vitesse",
    shortName: "Vitesse",
    code: "VIT",
    city: "Arnhem",
    primaryColor: "#FFCD00",
    secondaryColor: "#000000",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Logo_Vitesse_2022.svg/100px-Logo_Vitesse_2022.svg.png",
    league: "eredivisie",
  },
  {
    id: "heerenveen",
    name: "SC Heerenveen",
    shortName: "Heerenveen",
    code: "HEE",
    city: "Heerenveen",
    primaryColor: "#003DA5",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/SC_Heerenveen_Logo.svg/100px-SC_Heerenveen_Logo.svg.png",
    league: "eredivisie",
  },
  {
    id: "groningen",
    name: "FC Groningen",
    shortName: "Groningen",
    code: "GRO",
    city: "Groningen",
    primaryColor: "#006F3C",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/FC_Groningen_logo.svg/100px-FC_Groningen_logo.svg.png",
    league: "eredivisie",
  },
  {
    id: "sparta",
    name: "Sparta Rotterdam",
    shortName: "Sparta",
    code: "SPA",
    city: "Rotterdam",
    primaryColor: "#C8102E",
    secondaryColor: "#000000",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Sparta_Rotterdam.svg/100px-Sparta_Rotterdam.svg.png",
    league: "eredivisie",
  },
  {
    id: "nec",
    name: "NEC Nijmegen",
    shortName: "NEC",
    code: "NEC",
    city: "Nijmegen",
    primaryColor: "#003DA5",
    secondaryColor: "#FFCD00",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/4/44/NEC_Nijmegen.svg/100px-NEC_Nijmegen.svg.png",
    league: "eredivisie",
  },
  {
    id: "go_ahead",
    name: "Go Ahead Eagles",
    shortName: "Go Ahead",
    code: "GAE",
    city: "Deventer",
    primaryColor: "#FFCD00",
    secondaryColor: "#003DA5",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Go_Ahead_Eagles_logo.svg/100px-Go_Ahead_Eagles_logo.svg.png",
    league: "eredivisie",
  },
  {
    id: "pec_zwolle",
    name: "PEC Zwolle",
    shortName: "PEC Zwolle",
    code: "PEC",
    city: "Zwolle",
    primaryColor: "#003DA5",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/PEC_Zwolle.svg/100px-PEC_Zwolle.svg.png",
    league: "eredivisie",
  },
  {
    id: "heracles",
    name: "Heracles Almelo",
    shortName: "Heracles",
    code: "HER",
    city: "Almelo",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Heracles_Almelo.svg/100px-Heracles_Almelo.svg.png",
    league: "eredivisie",
  },
  {
    id: "almere",
    name: "Almere City FC",
    shortName: "Almere",
    code: "ALM",
    city: "Almere",
    primaryColor: "#E31E2E",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/Almere_City_FC_logo.svg/100px-Almere_City_FC_logo.svg.png",
    league: "eredivisie",
  },
  {
    id: "fortuna",
    name: "Fortuna Sittard",
    shortName: "Fortuna",
    code: "FOR",
    city: "Sittard",
    primaryColor: "#FFCD00",
    secondaryColor: "#006F3C",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/Fortuna_Sittard_logo.svg/100px-Fortuna_Sittard_logo.svg.png",
    league: "eredivisie",
  },
  {
    id: "rkc",
    name: "RKC Waalwijk",
    shortName: "RKC",
    code: "RKC",
    city: "Waalwijk",
    primaryColor: "#FFCD00",
    secondaryColor: "#003DA5",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/4/40/RKC_Waalwijk.svg/100px-RKC_Waalwijk.svg.png",
    league: "eredivisie",
  },
  {
    id: "cambuur",
    name: "SC Cambuur",
    shortName: "Cambuur",
    code: "CAM",
    city: "Leeuwarden",
    primaryColor: "#FFCD00",
    secondaryColor: "#003DA5",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/Cambuur_Leeuwarden.svg/100px-Cambuur_Leeuwarden.svg.png",
    league: "eerste_divisie",
  },
  // ── Eerste Divisie ─────────────────────────────────────────────────────────
  {
    id: "nac",
    name: "NAC Breda",
    shortName: "NAC",
    code: "NAC",
    city: "Breda",
    primaryColor: "#FFCD00",
    secondaryColor: "#000000",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/1/15/NAC_Breda.svg/100px-NAC_Breda.svg.png",
    league: "eerste_divisie",
  },
  {
    id: "willem2",
    name: "Willem II",
    shortName: "Willem II",
    code: "WIL",
    city: "Tilburg",
    primaryColor: "#E31E2E",
    secondaryColor: "#003DA5",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Willem_II_Tilburg_Logo.svg/100px-Willem_II_Tilburg_Logo.svg.png",
    league: "eerste_divisie",
  },
  {
    id: "den_haag",
    name: "ADO Den Haag",
    shortName: "Den Haag",
    code: "ADO",
    city: "Den Haag",
    primaryColor: "#FFCD00",
    secondaryColor: "#006F3C",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/ADO_Den_Haag_logo.svg/100px-ADO_Den_Haag_logo.svg.png",
    league: "eerste_divisie",
  },
  {
    id: "roda",
    name: "Roda JC Kerkrade",
    shortName: "Roda JC",
    code: "ROD",
    city: "Kerkrade",
    primaryColor: "#FFCD00",
    secondaryColor: "#000000",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Roda_JC.svg/100px-Roda_JC.svg.png",
    league: "eerste_divisie",
  },
  {
    id: "excelsior",
    name: "Excelsior Rotterdam",
    shortName: "Excelsior",
    code: "EXC",
    city: "Rotterdam",
    primaryColor: "#E31E2E",
    secondaryColor: "#000000",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Excelsior_Rotterdam.svg/100px-Excelsior_Rotterdam.svg.png",
    league: "eerste_divisie",
  },
  {
    id: "jong_ajax",
    name: "Jong Ajax",
    shortName: "Jong Ajax",
    code: "JA",
    city: "Amsterdam",
    primaryColor: "#D2122E",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/7/79/Ajax_Amsterdam.svg/100px-Ajax_Amsterdam.svg.png",
    league: "eerste_divisie",
  },
  {
    id: "jong_psv",
    name: "Jong PSV",
    shortName: "Jong PSV",
    code: "JPSV",
    city: "Eindhoven",
    primaryColor: "#E31E2E",
    secondaryColor: "#FFFFFF",
    logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/PSV_Eindhoven.svg/100px-PSV_Eindhoven.svg.png",
    league: "eerste_divisie",
  },
  // ── Amateur / local ───────────────────────────────────────────────────────
  {
    id: "schoonhoven",
    name: "Schoonhoven FC",
    shortName: "Schoonhoven",
    code: "SHV",
    city: "Schoonhoven",
    primaryColor: "#0A2540",
    secondaryColor: "#4FA9E6",
    logoUrl: "",
    league: "amateur",
  },
];

// Quick lookup map by id
export const CLUB_BY_ID = Object.fromEntries(DUTCH_CLUBS.map((c) => [c.id, c]));

// Club selector groups for UI
export const CLUB_GROUPS = [
  { label: "Eredivisie", clubs: DUTCH_CLUBS.filter((c) => c.league === "eredivisie") },
  { label: "Eerste Divisie", clubs: DUTCH_CLUBS.filter((c) => c.league === "eerste_divisie") },
  { label: "Amateur", clubs: DUTCH_CLUBS.filter((c) => c.league === "amateur") },
];
